import type { AppConfig } from "../utils/config";

export const DEFAULT_STATION_CONFIG: AppConfig = {
  soc: "Pleiku SOC",
  soc_id: "1030",
  cookies: "",
  hubs: [
    "44-GLI An Khe Hub", "44-GLI Ayun Pa Hub", "44-GLI Chu Pah Hub",
    "44-GLI Chu Prong 02 Hub", "44-GLI Chu Prong Hub", "44-GLI Chu Puh Hub",
    "44-GLI Chu Se Hub", "44-GLI Dak Doa Hub", "44-GLI Duc Co Hub",
    "44-GLI Ia Grai Hub", "44-GLI Kbang Hub", "44-GLI Krong Pa Hub",
    "44-GLI Mang Yang Hub", "44-GLI MBH An Khe Hub", "44-GLI MBH Ayun Pa Hub",
    "44-GLI MBH Chu Prong Hub", "44-GLI MBH Dak Doa Hub", "44-GLI MBH Ia Grai Hub",
    "44-GLI Phu Thien Hub", "44-GLI Pleiku 02 Hub", "44-GLI Pleiku 03 Hub",
    "44-GLI Pleiku 04 Hub", "44-GLI Pleiku Hub",
  ],
  hub_ids: {
    "44-GLI An Khe Hub": "1069",
    "44-GLI Ayun Pa Hub": "1418",
    "44-GLI Chu Pah Hub": "1890",
    "44-GLI Chu Prong 02 Hub": "2389",
    "44-GLI Chu Prong Hub": "1033",
    "44-GLI Chu Puh Hub": "2186",
    "44-GLI Chu Se Hub": "1128",
    "44-GLI Dak Doa Hub": "1031",
    "44-GLI Duc Co Hub": "1415",
    "44-GLI Ia Grai Hub": "1251",
    "44-GLI Kbang Hub": "2187",
    "44-GLI Krong Pa Hub": "2138",
    "44-GLI Mang Yang Hub": "2124",
    "44-GLI MBH An Khe Hub": "4102",
    "44-GLI MBH Ayun Pa Hub": "4103",
    "44-GLI MBH Chu Prong Hub": "5520",
    "44-GLI MBH Dak Doa Hub": "2009",
    "44-GLI MBH Ia Grai Hub": "4136",
    "44-GLI Phu Thien Hub": "2304",
    "44-GLI Pleiku 02 Hub": "1015",
    "44-GLI Pleiku 03 Hub": "1812",
    "44-GLI Pleiku 04 Hub": "3997",
    "44-GLI Pleiku Hub": "224",
  },
  socs: [
    "DN Mega SOC", "BD A Mega SOC", "BD B Mega SOC", "BN A Mega SOC",
    "BN B Mega SOC", "HCM Mega SOC", "HN SOC", "BMT SOC", "Kon Tum SOC",
    "Vinh SOC", "Cam Xuyen SOC", "Tuy Phuoc SOC", "Tuy Hoa SOC",
    "Quang Ngai SOC", "Dien Khanh SOC", "Dong Hoi SOC", "Phan Rang SOC",
    "Duc Trong SOC", "Gia Nghia SOC",
  ],
  soc_ids: {
    "DN Mega SOC": "3983",
    "BD A Mega SOC": "2490",
    "BD B Mega SOC": "4110",
    "BN A Mega SOC": "1701",
    "BN B Mega SOC": "1959",
    "HCM Mega SOC": "1707",
    "HN SOC": "6",
    "BMT SOC": "725",
    "Kon Tum SOC": "1769",
    "Vinh SOC": "549",
    "Cam Xuyen SOC": "834",
    "Tuy Phuoc SOC": "324",
    "Tuy Hoa SOC": "1791",
    "Quang Ngai SOC": "1333",
    "Dien Khanh SOC": "288",
    "Dong Hoi SOC": "672",
    "Phan Rang SOC": "1579",
    "Duc Trong SOC": "1041",
    "Gia Nghia SOC": "1467",
  },
  group_socs: {
    "DN Mega SOC": [
      "DN Mega SOC", "Vinh SOC", "Cam Xuyen SOC", "Tuy Phuoc SOC",
      "Tuy Hoa SOC", "Quang Ngai SOC", "Dien Khanh SOC", "Dong Hoi SOC",
    ],
    "BD A Mega SOC": ["BD A Mega SOC", "Phan Rang SOC", "Duc Trong SOC"],
    "BMT SOC": ["BMT SOC", "Gia Nghia SOC"],
  },
  raw_group_socs_text:
    "DN Mega SOC @Vinh SOC @Cam Xuyen SOC @Tuy Phuoc SOC @Tuy Hoa SOC @Quang Ngai SOC @Dien Khanh SOC @Dong Hoi SOC\n" +
    "BD A Mega SOC @Phan Rang SOC @Duc Trong SOC\n" +
    "BMT SOC @Gia Nghia SOC",
  ggsheet_log_url: "",
};
